services:
  track-api:
    # run first: mvn install -DskipTests
    build:
      context: TrackApplication
    container_name: music-track-api
    image: track-api
    ports:
      - 8080:8080
    networks:
      - music-app
  pricing-api:
    # run first: mvn install -DskipTests
    build:
      context: PricingApplication
    container_name: music-pricing-api
    image: pricing-api
    ports:
      - 8081:8081
    networks:
      - music-app
    expose:
      - "8081"
networks:
  music-app:
    external: false
